---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./cluster16.yaml
  #- ./cluster16-vectorchord.yaml
  - ./scheduledbackup.yaml
  - ./prometheusrule.yaml
