---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  COREDNS_ADDR: "10.43.0.10"
  KUBE_VIP_ADDR: "172.16.0.210"
  SVC_MOSQUITTO_ADDR: "172.16.0.215"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
  NODE_CIDR: "172.16.0.0/24"
